import VersoManual
import TextbookTemplate.Meta.Lean
import TextbookTemplate.Papers

-- for the second example
import Mathlib.Data.Finset.Defs

-- for the third example
import Mathlib.Data.Finset.Card

-- This gets access to most of the manual genre (which is also useful for textbooks)
open Verso.Genre Manual

-- This gets access to Lean code that's in code blocks, elaborated in the same process and
-- environment as Verso
open Verso.Genre.Manual.InlineLean

-- for cardinality symbol
open Finset

open TextbookTemplate

set_option pp.rawOnError true



#doc (Manual) "Understanding error messages" =>

# Understanding error messages

We now want to understand how to read the error messages of `grind`.
This is the error message from before:

```lean +error (name := noInter) -show
theorem exists_subset_or_subset_of_two_mul_lt_card''
    {α : Type*} [DecidableEq α] {X Y : Finset α} {n : ℕ}
    (hXY : 2 * n < #(X ∪ Y)) :
    ∃ C : Finset α, n < #C ∧ (C ⊆ X ∨ C ⊆ Y) := by
  grind
```

```leanOutput noInter
`grind` failed
case grind.2
α : Type u_1
inst : DecidableEq α
X Y : Finset α
n : ℕ
hXY : 2 * n < #(X ∪ Y)
h : ∀ (a : Finset α), #a ≤ n ∨ ¬a ⊆ X ∧ ¬a ⊆ Y
left : ¬X ∪ Y ⊆ X
right : ¬X ∪ Y ⊆ Y
w : α
h_3 : ¬(w ∈ X ∪ Y → w ∈ X)
w_1 : α
h_5 : ¬(w_1 ∈ X ∪ Y → w_1 ∈ Y)
⊢ False
[grind] Goal diagnostics
  [facts] Asserted facts
  [eqc] True propositions
  [eqc] False propositions
  [cases] Case analyses
  [ematch] E-matching patterns
  [cutsat] Assignment satisfying linear constraints

[grind] Diagnostics
```

At the top you can see the goal state that `grind` got stuck on.
If there are several open goals, it only displays the first one.
You can see here that we are in a case generated by a case split somewhere.
To see how we got there we can set the option `trace.grind.split` to true to get

```savedLean (name := traceSplit) +error -show
set_option trace.grind.split true in
theorem exists_subset_or_subset_of_two_mul_lt_card''' {α}
    [DecidableEq α] {X Y : Finset α} {n : ℕ}
    (hXY : 2 * n < #(X ∪ Y)) :
    ∃ C : Finset α, n < #C ∧ (C ⊆ X ∨ C ⊆ Y) := by
  grind
```

```leanOutput traceSplit
[grind.split] #(X ∪ Y) ≤ n ∨ ¬X ∪ Y ⊆ X ∧ ¬X ∪ Y ⊆ Y, generation: 1
```

Here we can see the statement `grind` has split on, which is `h` applied to `X ∪ Y`.

Question: What does the asserted facts section actually do?

The next thing to understand is that `grind` doesn't work by rewriting with terms that it considers to be equal.
Instead, it maintains equivalence classes.
This is also a way to discover contradictions.
If two different constructors of the same type (e.g. `True` and `False` or `some a` and `none`) are put in the same equivalence class, `grind` has found a contradiction and finishes the proof.

The two main equivalence classes are those of true and false propositions which you can see as output in the error message.
It can also show other equivalence classes.
That isn't the case in our example but it is here:

```lean +error (name := missingHyp)
example (n k : ℕ) (h1 : 2 * n = k) : k = 5 := by
  grind
```

Of course this statement is clearly missing a hypothesis for it to be true.
In a more complicated example you might not directly see the missing hypothesis but could maybe figure it out by looking at the error message:

```leanOutput missingHyp
`grind` failed
case grind
n k : ℕ
h1 : 2 * n = k
h : ¬k = 5
⊢ False
[grind] Goal diagnostics
  [facts] Asserted facts
  [eqc] False propositions
  [eqc] Equivalence classes
  [cutsat] Assignment satisfying linear constraints
  [ring] Ring `Lean.Grind.Ring.OfSemiring.Q ℕ`
```

You can see that here we have more equivalence classes than just those of true and false propositions.

Next, our error message from the beginning of this section has a section on cases.
Here you can see on which terms case splits were performed.
We will get into case splits in the next section.

Afterwards there is a section called "ematch".
E-matching is how `grind` uses tagged lemmas.
We will discuss this in detail in a later section.

Then both error messages feature sections called `cutsat` and the later error message in this section has a section about `ring`.
These are two examples of satellite solvers that `grind` employs to solve problems of specific types.
They are different from the Mathlib tactics of the same names because `grind` is supposed to work Mathlib-free.
You can however imagine them to work similarly.
